# Generated by Django 3.0.8 on 2020-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id', 'date_created'], name='posts_comme_post_id_a2f65b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['date_created', '-pins'], name='posts_post_date_cr_08b9ed_idx'),
        ),
    ]
